INSERT INTO raw_ingredients (name, category) VALUES ('Tomate', 'Verdura');
INSERT INTO raw_ingredients (name, category) VALUES ('Cebolla', 'Verdura');
INSERT INTO raw_ingredients (name, category) VALUES ('Ajo', 'Verdura');
INSERT INTO raw_ingredients (name, category) VALUES ('Zanahoria', 'Verdura');
INSERT INTO raw_ingredients (name, category) VALUES ('Papa', 'Verdura');
INSERT INTO raw_ingredients (name, category) VALUES ('Lechuga', 'Verdura');
INSERT INTO raw_ingredients (name, category) VALUES ('Espinaca', 'Verdura');
INSERT INTO raw_ingredients (name, category) VALUES ('Pepino', 'Verdura');
INSERT INTO raw_ingredients (name, category) VALUES ('Pimentón', 'Verdura');
INSERT INTO raw_ingredients (name, category) VALUES ('Brócoli', 'Verdura');
INSERT INTO raw_ingredients (name, category) VALUES ('Coliflor', 'Verdura');
INSERT INTO raw_ingredients (name, category) VALUES ('Calabacín', 'Verdura');
INSERT INTO raw_ingredients (name, category) VALUES ('Apio', 'Verdura');
INSERT INTO raw_ingredients (name, category) VALUES ('Berenjena', 'Verdura');
INSERT INTO raw_ingredients (name, category) VALUES ('Repollo', 'Verdura');
INSERT INTO raw_ingredients (name, category) VALUES ('Manzana', 'Fruta');
INSERT INTO raw_ingredients (name, category) VALUES ('Banano', 'Fruta');
INSERT INTO raw_ingredients (name, category) VALUES ('Naranja', 'Fruta');
INSERT INTO raw_ingredients (name, category) VALUES ('Fresa', 'Fruta');
INSERT INTO raw_ingredients (name, category) VALUES ('Piña', 'Fruta');
INSERT INTO raw_ingredients (name, category) VALUES ('Mango', 'Fruta');
INSERT INTO raw_ingredients (name, category) VALUES ('Uva', 'Fruta');
INSERT INTO raw_ingredients (name, category) VALUES ('Melón', 'Fruta');
INSERT INTO raw_ingredients (name, category) VALUES ('Papaya', 'Fruta');
INSERT INTO raw_ingredients (name, category) VALUES ('Pollo entero', 'Pollo');
INSERT INTO raw_ingredients (name, category) VALUES ('Pechuga de pollo', 'Pollo');
INSERT INTO raw_ingredients (name, category) VALUES ('Muslo de pollo', 'Pollo');
INSERT INTO raw_ingredients (name, category) VALUES ('Ala de pollo', 'Pollo');
INSERT INTO raw_ingredients (name, category) VALUES ('Pierna de pollo', 'Pollo');
INSERT INTO raw_ingredients (name, category) VALUES ('Cuello de pollo', 'Pollo');
INSERT INTO raw_ingredients (name, category) VALUES ('Molleja de pollo', 'Pollo');
INSERT INTO raw_ingredients (name, category) VALUES ('Hígado de pollo', 'Pollo');
INSERT INTO raw_ingredients (name, category) VALUES ('Patas de pollo', 'Pollo');
INSERT INTO raw_ingredients (name, category) VALUES ('Carne de res', 'Res');
INSERT INTO raw_ingredients (name, category) VALUES ('Lomo de res', 'Res');
INSERT INTO raw_ingredients (name, category) VALUES ('Costilla de res', 'Res');
INSERT INTO raw_ingredients (name, category) VALUES ('Hígado de res', 'Res');
INSERT INTO raw_ingredients (name, category) VALUES ('Morrillo', 'Res');
INSERT INTO raw_ingredients (name, category) VALUES ('Falda de res', 'Res');
INSERT INTO raw_ingredients (name, category) VALUES ('Pulpa negra', 'Res');
INSERT INTO raw_ingredients (name, category) VALUES ('Posta', 'Res');
INSERT INTO raw_ingredients (name, category) VALUES ('Rabo de res', 'Res');
INSERT INTO raw_ingredients (name, category) VALUES ('Carne de cerdo', 'Cerdo');
INSERT INTO raw_ingredients (name, category) VALUES ('Costilla de cerdo', 'Cerdo');
INSERT INTO raw_ingredients (name, category) VALUES ('Lomo de cerdo', 'Cerdo');
INSERT INTO raw_ingredients (name, category) VALUES ('Chuleta de cerdo', 'Cerdo');
INSERT INTO raw_ingredients (name, category) VALUES ('Pierna de cerdo', 'Cerdo');
INSERT INTO raw_ingredients (name, category) VALUES ('Tocino', 'Cerdo');
INSERT INTO raw_ingredients (name, category) VALUES ('Manitas de cerdo', 'Cerdo');
INSERT INTO raw_ingredients (name, category) VALUES ('Chicharrón', 'Cerdo');
INSERT INTO raw_ingredients (name, category) VALUES ('Arroz', 'Cereal');
INSERT INTO raw_ingredients (name, category) VALUES ('Pan', 'Cereal');
INSERT INTO raw_ingredients (name, category) VALUES ('Pasta', 'Cereal');
INSERT INTO raw_ingredients (name, category) VALUES ('Frijoles', 'Legumbre');
INSERT INTO raw_ingredients (name, category) VALUES ('Lentejas', 'Legumbre');
INSERT INTO raw_ingredients (name, category) VALUES ('Garbanzos', 'Legumbre');
INSERT INTO raw_ingredients (name, category) VALUES ('Queso', 'Lácteo');
INSERT INTO raw_ingredients (name, category) VALUES ('Leche', 'Lácteo');
INSERT INTO raw_ingredients (name, category) VALUES ('Mantequilla', 'Grasa');
INSERT INTO raw_ingredients (name, category) VALUES ('Aceite vegetal', 'Grasa');
INSERT INTO raw_ingredients (name, category) VALUES ('Aceite de oliva', 'Grasa');
INSERT INTO raw_ingredients (name, category) VALUES ('Sal', 'Condimento');
INSERT INTO raw_ingredients (name, category) VALUES ('Azúcar', 'Condimento');
INSERT INTO raw_ingredients (name, category) VALUES ('Pimienta', 'Condimento');
INSERT INTO raw_ingredients (name, category) VALUES ('Comino', 'Condimento');
INSERT INTO raw_ingredients (name, category) VALUES ('Canela', 'Condimento');
INSERT INTO raw_ingredients (name, category) VALUES ('Laurel', 'Condimento');
INSERT INTO raw_ingredients (name, category) VALUES ('Harina de trigo', 'Harina');
INSERT INTO raw_ingredients (name, category) VALUES ('Harina de maíz', 'Harina');
INSERT INTO raw_ingredients (name, category) VALUES ('Harina de avena', 'Harina');
INSERT INTO raw_ingredients (name, category) VALUES ('Harina de arroz', 'Harina');
INSERT INTO raw_ingredients (name, category) VALUES ('Harina de yuca', 'Harina');
INSERT INTO raw_ingredients (name, category) VALUES ('Maíz en grano', 'Grano');
INSERT INTO raw_ingredients (name, category) VALUES ('Avena', 'Grano');
INSERT INTO raw_ingredients (name, category) VALUES ('Cebada', 'Grano');
INSERT INTO raw_ingredients (name, category) VALUES ('Quinoa', 'Grano');
INSERT INTO raw_ingredients (name, category) VALUES ('Arroz integral', 'Grano');
INSERT INTO raw_ingredients (name, category) VALUES ('Trigo en grano', 'Grano');
INSERT INTO raw_ingredients (name, category) VALUES ('Centeno', 'Grano');
INSERT INTO raw_ingredients (name, category) VALUES ('Camarón', 'Marisco');
INSERT INTO raw_ingredients (name, category) VALUES ('Langostino', 'Marisco');
INSERT INTO raw_ingredients (name, category) VALUES ('Pulpo', 'Marisco');
INSERT INTO raw_ingredients (name, category) VALUES ('Calamar', 'Marisco');
INSERT INTO raw_ingredients (name, category) VALUES ('Mejillón', 'Marisco');
INSERT INTO raw_ingredients (name, category) VALUES ('Almeja', 'Marisco');
INSERT INTO raw_ingredients (name, category) VALUES ('Ostra', 'Marisco');
INSERT INTO raw_ingredients (name, category) VALUES ('Pescado blanco', 'Pescado');
INSERT INTO raw_ingredients (name, category) VALUES ('Tilapia', 'Pescado');
INSERT INTO raw_ingredients (name, category) VALUES ('Salmón', 'Pescado');
INSERT INTO raw_ingredients (name, category) VALUES ('Atún', 'Pescado');
INSERT INTO raw_ingredients (name, category) VALUES ('Bacalao', 'Pescado');
INSERT INTO raw_ingredients (name, category) VALUES ('Trucha', 'Pescado');
INSERT INTO raw_ingredients (name, category) VALUES ('Merluza', 'Pescado');
INSERT INTO raw_ingredients (name, category) VALUES ('Champiñón', 'Hongo');
INSERT INTO raw_ingredients (name, category) VALUES ('Seta', 'Hongo');
INSERT INTO raw_ingredients (name, category) VALUES ('Hongo shiitake', 'Hongo');
INSERT INTO raw_ingredients (name, category) VALUES ('Hongo portobello', 'Hongo');
INSERT INTO raw_ingredients (name, category) VALUES ('Punta de anca', 'Res');
INSERT INTO raw_ingredients (name, category) VALUES ('Picaña', 'Res');
INSERT INTO raw_ingredients (name, category) VALUES ('Sobrebarriga', 'Res');
INSERT INTO raw_ingredients (name, category) VALUES ('Entrecot', 'Res');
INSERT INTO raw_ingredients (name, category) VALUES ('Bistec', 'Res');
INSERT INTO raw_ingredients (name, category) VALUES ('Asado de tira', 'Res');
INSERT INTO raw_ingredients (name, category) VALUES ('Churrasco', 'Res');
INSERT INTO raw_ingredients (name, category) VALUES ('Vacío', 'Res');
INSERT INTO raw_ingredients (name, category) VALUES ('Tapa de cuadril', 'Res');
INSERT INTO raw_ingredients (name, category) VALUES ('Filete de pechuga', 'Pollo');
INSERT INTO raw_ingredients (name, category) VALUES ('Contramuslo', 'Pollo');
INSERT INTO raw_ingredients (name, category) VALUES ('Menudencias de pollo', 'Pollo');
INSERT INTO raw_ingredients (name, category) VALUES ('Carcasa de pollo', 'Pollo');
INSERT INTO raw_ingredients (name, category) VALUES ('Bondiola', 'Cerdo');
INSERT INTO raw_ingredients (name, category) VALUES ('Lomo embuchado', 'Cerdo');
INSERT INTO raw_ingredients (name, category) VALUES ('Panceta', 'Cerdo');
INSERT INTO raw_ingredients (name, category) VALUES ('Cabeza de cerdo', 'Cerdo');
INSERT INTO raw_ingredients (name, category) VALUES ('Costillar', 'Cerdo');
INSERT INTO raw_ingredients (name, category) VALUES ('Solomillo', 'Cerdo');
INSERT INTO raw_ingredients (name, category) VALUES ('Langosta', 'Marisco');
INSERT INTO raw_ingredients (name, category) VALUES ('Percebe', 'Marisco');
INSERT INTO raw_ingredients (name, category) VALUES ('Bogavante', 'Marisco');
INSERT INTO raw_ingredients (name, category) VALUES ('Cangrejo', 'Marisco');
INSERT INTO raw_ingredients (name, category) VALUES ('Dorado', 'Pescado');
INSERT INTO raw_ingredients (name, category) VALUES ('Corvina', 'Pescado');
INSERT INTO raw_ingredients (name, category) VALUES ('Bagre', 'Pescado');
INSERT INTO raw_ingredients (name, category) VALUES ('Mero', 'Pescado');
INSERT INTO raw_ingredients (name, category) VALUES ('Róbalo', 'Pescado');
INSERT INTO raw_ingredients (name, category) VALUES ('Sierra', 'Pescado');
INSERT INTO raw_ingredients (name, category) VALUES ('Tomate chonto', 'Verdura');
INSERT INTO raw_ingredients (name, category) VALUES ('Tomate larga vida', 'Verdura');
INSERT INTO raw_ingredients (name, category) VALUES ('Tomate cherry', 'Verdura');
INSERT INTO raw_ingredients (name, category) VALUES ('Tomate pera', 'Verdura');
INSERT INTO raw_ingredients (name, category) VALUES ('Cebolla cabezona', 'Verdura');
INSERT INTO raw_ingredients (name, category) VALUES ('Cebolla larga', 'Verdura');
INSERT INTO raw_ingredients (name, category) VALUES ('Papa criolla', 'Verdura');
INSERT INTO raw_ingredients (name, category) VALUES ('Papa pastusa', 'Verdura');
INSERT INTO raw_ingredients (name, category) VALUES ('Papa sabanera', 'Verdura');
INSERT INTO raw_ingredients (name, category) VALUES ('Zanahoria baby', 'Verdura');
INSERT INTO raw_ingredients (name, category) VALUES ('Lechuga crespa', 'Verdura');
INSERT INTO raw_ingredients (name, category) VALUES ('Lechuga romana', 'Verdura');
INSERT INTO raw_ingredients (name, category) VALUES ('Lechuga batavia', 'Verdura');
INSERT INTO raw_ingredients (name, category) VALUES ('Pimentón rojo', 'Verdura');
INSERT INTO raw_ingredients (name, category) VALUES ('Pimentón verde', 'Verdura');
INSERT INTO raw_ingredients (name, category) VALUES ('Pimentón amarillo', 'Verdura');
INSERT INTO raw_ingredients (name, category) VALUES ('Ají dulce', 'Verdura');
INSERT INTO raw_ingredients (name, category) VALUES ('Ají picante', 'Verdura');
INSERT INTO raw_ingredients (name, category) VALUES ('Calabacín verde', 'Verdura');
INSERT INTO raw_ingredients (name, category) VALUES ('Calabacín amarillo', 'Verdura');
INSERT INTO raw_ingredients (name, category) VALUES ('Repollo verde', 'Verdura');
INSERT INTO raw_ingredients (name, category) VALUES ('Repollo morado', 'Verdura');
INSERT INTO raw_ingredients (name, category) VALUES ('Espinaca baby', 'Verdura');
INSERT INTO raw_ingredients (name, category) VALUES ('Banano bocadillo', 'Fruta');
INSERT INTO raw_ingredients (name, category) VALUES ('Banano hartón', 'Fruta');
INSERT INTO raw_ingredients (name, category) VALUES ('Manzana roja', 'Fruta');
INSERT INTO raw_ingredients (name, category) VALUES ('Manzana verde', 'Fruta');
INSERT INTO raw_ingredients (name, category) VALUES ('Naranja valencia', 'Fruta');
INSERT INTO raw_ingredients (name, category) VALUES ('Naranja tangelo', 'Fruta');
INSERT INTO raw_ingredients (name, category) VALUES ('Piña oro miel', 'Fruta');
INSERT INTO raw_ingredients (name, category) VALUES ('Piña perolera', 'Fruta');
INSERT INTO raw_ingredients (name, category) VALUES ('Mango tommy', 'Fruta');
INSERT INTO raw_ingredients (name, category) VALUES ('Mango de azúcar', 'Fruta');
INSERT INTO raw_ingredients (name, category) VALUES ('Papaya maradol', 'Fruta');
INSERT INTO raw_ingredients (name, category) VALUES ('Papaya hawaiana', 'Fruta');
INSERT INTO raw_ingredients (name, category) VALUES ('Queso costeño', 'Lácteo');
INSERT INTO raw_ingredients (name, category) VALUES ('Queso campesino', 'Lácteo');
INSERT INTO raw_ingredients (name, category) VALUES ('Queso doble crema', 'Lácteo');
INSERT INTO raw_ingredients (name, category) VALUES ('Queso mozarella', 'Lácteo');
INSERT INTO raw_ingredients (name, category) VALUES ('Queso cuajada', 'Lácteo');
INSERT INTO raw_ingredients (name, category) VALUES ('Yogur natural', 'Lácteo');
INSERT INTO raw_ingredients (name, category) VALUES ('Yogur de frutas', 'Lácteo');
INSERT INTO raw_ingredients (name, category) VALUES ('Leche entera', 'Lácteo');
INSERT INTO raw_ingredients (name, category) VALUES ('Leche deslactosada', 'Lácteo');
INSERT INTO raw_ingredients (name, category) VALUES ('Leche en polvo', 'Lácteo');
INSERT INTO raw_ingredients (name, category) VALUES ('Ají molido', 'Condimento');
INSERT INTO raw_ingredients (name, category) VALUES ('Pimienta negra', 'Condimento');
INSERT INTO raw_ingredients (name, category) VALUES ('Pimienta blanca', 'Condimento');
INSERT INTO raw_ingredients (name, category) VALUES ('Canela en astilla', 'Condimento');
INSERT INTO raw_ingredients (name, category) VALUES ('Canela en polvo', 'Condimento');
INSERT INTO raw_ingredients (name, category) VALUES ('Cúrcuma', 'Condimento');
INSERT INTO raw_ingredients (name, category) VALUES ('Orégano seco', 'Condimento');
INSERT INTO raw_ingredients (name, category) VALUES ('Tomillo', 'Condimento');
INSERT INTO raw_ingredients (name, category) VALUES ('Laurel seco', 'Condimento');
INSERT INTO raw_ingredients (name, category) VALUES ('Clavo de olor', 'Condimento');