name: Go Integration Test Report

on:

  pull_request:
    branches: [ master ]
    paths:
      - "restaurant_manager/**"
      - ".github/workflows/go-test-report.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install go-test-report
        run: go install github.com/vakenbolt/go-test-report@latest

      - name: Run integration tests and generate report
        run: |
          go test -json ./restaurant_manager/tests/integration/... | ~/go/bin/go-test-report 